### ISSUE TITLE
How to print data from getBlockByHash?

### ISSUE THREAD

**Issue by thatsailorman** [flavienbwk/blockchain-php#1]
First off, nice code! I'm playing around with it for a bit, everything seems to work just fine but I'm kind of stuck at one point...

When using this code:
$Blockchain->getBlockByHash("blockchain.dat", "INSERT_THE_BLOCK_HASH_HERE");

How would I echo the data from that certain block?

For example; I want to echo both the block position and the data. What would be the most simple or easy way to do so?

Thanks in advance!

**Comment by flavienbwk** [comment]
Hello @thatsailorman, 

Thank you for the compliment !

`$Blockchain->getBlockByHash("blockchain.dat", "INSERT_THE_BLOCK_HASH_HERE");` returns an instance of [`Block`](https://github.com/flavienbwk/blockchain-php/blob/master/src/Block.php), which has getters.

So for example :

```
$Block = $Blockchain->getBlockByHash("blockchain.dat", "INSERT_THE_BLOCK_HASH_HERE");
echo "Position: " . $Block->getOffset();
echo "Data: " . json_encode($Block->getData());
```

Does this help you ?

**Comment by thatsailorman** [comment]
Hi,

I was really close... but I couldn't get it to work properly. Now it does. :) Thank you for helping out.

**Comment by flavienbwk** [comment]
Perfect, good continuation !
